on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
    branches:
      - main


name: Build robot

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and possibly release
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: zulu
          cache: 'gradle'
      - name: Package
        run: date +%y.%m.%d.${{github.run_number}} > version.txt && ./gradlew --no-daemon shadowJar
      - uses: actions/upload-artifact@v4.3.1
        with:
          name: jar
          path: build/libs/nfc4pc-*.jar
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: softprops/action-gh-release@v2.0.4
        with:
          files: |
            build/libs/nfc4pc-*.jar
          fail_on_unmatched_files: true
          body: Release ${{ github.ref_name }}
          prerelease: true # manually promoted
